env:
  global:
   - secure: "aIByKkg5uTXD69L4/+MaH31gEJadJEfjGZwFHhMH/YLpOyqSIL9aV2qRJn9mUtaghpFbuLqakMNJfZLUemtqKiTMi7z3TjhTLNha4fx//WaZYemCyWvyBccwoSUDBZ947+MyHGlQhU2Kehe/2lde4U4DiR0m6ZUQOTWjkRmA7VFQa+wSmzQTriTdQ7R8X841I7NGWiWEn/shtTf/wvdSu0ITRiniEoU21IrOLDHe2keEql7UOLqAcUDKkFzPAbGiRFA/zwBXDMqVX19txjW1ZJCY5eiE5P6Ng0tQ4OkiXyDumJgFm58q9uN4/ZPStGd3BrrFgnRWk4ZekskRo+GGjxy5HthWTNJP7+1Mzh6whYiTFSNZtxD9wYhsM9Mo5I1V+nDP2ujX/wcv9PTTqBKDOkFjBDjIAWhZx0WWpU+PwbsUhQfI95Ve9F8g7kj29+O4EsI8HTFYfQZiZxfm/ekS01TrTEtkNTN0GLUZk9pBoJrIwKidb1dR/yi93uWYpzHQiUEDTauJRebSv/D3yZ9ZMxL4CIYX/8sHQvX1mQfKNXgRoQmRQA46WIbPh1zwv7XMM9PftsL2sBza8CdLTZ4HgJIN+0S2CfOfS3SbXkOHnUYOgpIAZBJTTVJua6mU52Wz3SUisHFHID7bWpI5T/6RFVGcwakOw8WfgtxUmdCTMUY="






dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
   coverity_scan:
    project:
      name: selassje/cppLockFreeQueue
      description: lock free Queue
    notification_email: selassje@gmail.com
    build_command_prepend: cd build/gnu 
    build_command:  cmake --build .
    branch_pattern: coverity_scan

   apt:

    packages:
      - gcc-6
      - g++-6
      - cmake
install:
      - pip install --user conan
      
script:
  - cmake --build . 