dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
install:
      - pip install --user conan
script:
      - cd build/gnu
      - export CC=/usr/bin/gcc-6
      - export CXX=/usr/bin/g++-6
      - export CMAKE_GENERATOR="Unix Makefiles"
      - bash  build.sh
      - cd ../../bin
      - ./lfQueueTest