env:
  global:
   - secure: "wFWSSD1JjI6EW1ttRvuRK3fQju5PC60O6ERz+NjBFIq4NEq9eWT0R19lcFMBeqDSy2kL0PIwgprMqpiNHiC0uOD44vSRnUkQvo+OXwiBvFAgJSY3sm7NUnwDrfdQs3S7nYiEMu6d7L94FS+KQQhkC1ZpBtFSb/nwvvA5mJCf5bkGMHGJPLfc9PhTmyqqafV1qDzCvxkaZyNDyl3Ls9wIfj4wwpC2Rg9RFODLppxpnDPApyQgo40m5DPLWVFM5wrnvqOHEQGAUrGvdJLOCR3fkbMDvPajK6625IL4T6DY6rmh5e6Z8WDEQDT68zX8UVYkhsJnmbyzLcyeOaUcpXESjloQmHm46raAqhpgSK8IRMl/xrP1Ls8fy65HWkpIM1P4bTOk/1tPJp0ThK8xWzvw+iAFrBp3I81lgXqQZ4QkIPZCNtV2d+weWRjywduQovfqZxnvQJn3+VZJNWpfNk30JKZfdcAlGwnqRFMLkzfdyAIabxYkuCVLFpBVISSBCoKbQBXqAFEfNfVtt1N4ya3lIuYAkCHXEnEmVcJ8PTzqt00rG9cZh70BCfWy9X4GiZm774orxM0Lv7joMrMt2iNRR49xOxb6rJ/IxTXl8n4frAFUtMJ4b84wD+Rkgm77PAe4ZJIPq3Fpsupi4E6jh8FxZRkXf/2ZaMSMBH4Eue8QtJg="

sudo: required
dist: bionic
language:
  - cpp
compiler:
  - gcc
  
install:
      - pip install --user conan
      - if [ ! -z "${ENABLE_COVERITY_SCAN}" ]; then  pip install --user cpp-coveralls; fi
addons:
   coverity_scan:
    project:
      name: selassje/cppLockFreeQueue
      description: lock free Queue
    notification_email: przemkoz85@gmail.com
    build_command_prepend: cd build/gnu
    build_command: ./build.sh
    branch_pattern: coverity_scan2



script:
    - cd build/gnu
    - ./build.sh
    - ./run.sh
    - if [ ! -z "${ENABLE_COVERITY_SCAN}" ]; then cpp-coveralls -r ../../ --gcov-options '\-lp' -i src;fi