env:
  global:
   - secure: "LofA3/GjKF49dY1pXJCDbuSOBBPu3XN+UXUuqF+Os1RHt8ROKiXt3Uijz/Vsf0/Kjn+Ip8cdKH+17OmHnAC4VsoJ3aoNI+44UnYPvHn5AO/7fkOr3VmJAE8EcnX0H1/9OpfUXq6ZOeg19UBqESozd2DmOTFNoAwtmgyUYHonMIo="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
